<?php
/**
	* impliments hook_help()
	*
	* @param path
*/

function emp_form_help($path, $arg) {
	switch ($path) {
		case "admin/help#emp_form":
			return t("Display links to nodes created on this date click here for github");
			break;
	}
}

//*********** Employee Form Menus**************

function emp_form_menu() {
	$items = array();
	// setup url */emp_form
	$items['emp_form/add'] = array(
		'title' => 'Employee Form',
		'type' => MENU_LOCAL_TASK,
		'description' => 'fill the emp details',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('emp_form_my_form'),
		'access arguments' => array('submit emp_form'),
	);

	$items['emp_form/view'] = array(
		'title' => 'List of Employee',
		'type' => MENU_LOCAL_TASK,
		'description' => 'fill the emp details',
		'page callback' => 'view_emp_form',
		'access arguments' => array('view view_emp_form'),
	);

	$items['emp_form/upload'] = array(
		'title' => 'Upload CSV File',
		'type' => MENU_LOCAL_TASK,
		'description' => 'Choose CSV File',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_csv'),
		'access arguments' => array('upload upload_csv'),
	);

        //******************** Sorting **********************

		$items['emp_form/view?order=field_emp_id&sort=desc'] = array(
		'title' => 'List of Employee',
		'type' => MENU_LOCAL_TASK,
		'description' => 'Order By Employee ID',
		'page callback' => 'view_emp',
		'access arguments' => array('view view_emp_form'),
		);

		//************ Edit Employee Data By ID *************

		$items['emp_form/edit/%'] = array(
			'title' => 'Edit Employee Data',
			'type' => MENU_LOCAL_TASK,
			'description' => 'Edit Employee By ID',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('edit_emp_data'),
			'access arguments' => array('edit emp_form_data_edit'),
		);

		//*********** Delete Employee Data By ID ************

		$items['emp_form/delete/%'] = array(
			'title' => 'Delete Employee Data',
			'type' => MENU_LOCAL_TASK,
			'description' => 'Delete Employee By ID',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('delete_emp_data'),
			'access arguments' => array('delete emp_form_data_delete'),
			// 'delivery callback' => 'ajax_deliver',
		);


	return $items;
}

//*********** Employee Form permission **************

function emp_form_permission() {
	return array(
		'submit emp_form' => array(
			'title' => t('submit emp_form'),
			'description' => t('Submit the emp_form form'),
		),

		'view view_emp_form' => array(
			'title' => t('View Form'),
			'description' => t('View Forms'),
		),

		'upload upload_csv' => array(
			'title' => t('Upload CSV'),
			'description' => t('Upload Csv file'),
		),

		'edit emp_form_data_edit' => array(
			'title' => t('Edit Employee Data'),
			'description' => t('Edit Employee by ID'),
		),

		'delete emp_form_data_delete' => array(
			'title' => t('Delete Employee Data'),
			'description' => t('Delete Employee Data by ID'),
		),
	);
}

//*********** Insert Individual Employee Data **************

function emp_form_my_form($form, &$form_state) {

	$form['emp_id'] = array(
		'#title' => t('Employee ID'),
		'#description' => t('The Employee\'s ID'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['emp_name'] = array(
		'#title' => t('Employee Name'),
		'#description' => t('The Employee\'s name'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['emp_des'] = array(
		'#title' => t('Employee Designation'),
		'#description' => t('The Employee\'s Designation'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['team_name'] = array(
		'#title' => t('Team Name'),
		'#description' => t('The Team\'s Name'),
		'#type' => 'textfield',
		'#required' => FALSE,
	);

	$form['join_date'] = array(
		'#type' => 'date_popup',
		'#date_format' => 'j F Y',
		'#title' => t('Joing Date'),
		'#datepicker_options' => array('yearRange' => "2005:+5"),
    	// '#date_label_position' => 'none',
	);

	$form['leave_date'] = array(
		'#type' => 'date_popup',
		'#date_format' => 'j F Y',
		'#title' => t('Leaving Date'),
		'#datepicker_options' => array('yearRange' => "2005:+5"),
    	// '#date_label_position' => 'none',
	);

	$form['status'] = array(
		'#title' => t('Employee Status'),
		'#type' => 'radios',
		'#description' => t('Employee Status'),
		'#required' => TRUE,
		'#options' =>array('Active' => t('Active'),'Inactive' => t('Inactive'),),
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	return $form;
}

function emp_form_my_form_validate($form, &$form_state) {

}

function emp_form_my_form_submit($form, &$form_state) {
	// Here you are use DB Query like insert data of employee in the table
	$emp_id_new = $form_state['values']['emp_id'];
	$emp_id = '';
	$rows =array();
	$results = db_query("select * from {emp_form_data} where emp_id = '$emp_id_new'");
		foreach ($results as $result) {
			$rows[] = array(
				$emp_id = $result->emp_id,
				$emp_name = $result->emp_name,
				$emp_des = $result->emp_des,
		);
	}
	if($emp_id_new != $emp_id) {
		db_insert('emp_form_data')
			->fields(array(
				'emp_name' => $form_state['values']['emp_name'],
				'emp_des' => $form_state['values']['emp_des'],
				'emp_id' => $form_state['values']['emp_id'],
				'team_name' => $form_state['values']['team_name'],
				'join_date' => $form_state['values']['join_date'],
				'leave_date' => $form_state['values']['leave_date'],
				'status' => $form_state['values']['status'],

			))
			->execute();

		drupal_set_message(t('Your Form submitted'));
		}
	else {
		drupal_set_message(t("Employee $emp_id is Already Exists as $emp_name"),'error');
	}
}


//*********** Upload CSV FILE **************

function upload_csv($form ,&$form_state) {

	$form['csv_file'] = array(
	'#type' => 'file',
	'#name' => 'files[csv_file]',
	'#title' => t('Choose a csv file'),
	'#title_display' => 'invisible',
	'#size' => 22,
	// '#upload_validators' => array('file_clean_name' => array()),
	);

	$form['upload'] = array(
		'#type' => 'submit',
		'#value' => 'Upload',
	);

	return $form;
}


function upload_csv_validate($form, &$form_state) {
		
		require_once(DRUPAL_ROOT.'/'.drupal_get_path('module', 'emp_form').'/parsecsv-for-php/parsecsv.lib.php');

		if(!isset($_FILES['files']['name']['csv_file']))
			drupal_set_message(t("ERROR upload CSV File"),'error');

		$file_path = $_FILES['files']['tmp_name']['csv_file'];
		// max_upload_code

		$csv = new ParseCsv\Csv($file_path);
		// Check CSV HEADER
		$std_header = array('emp_id' => 0, 'emp_name' => 0, 'emp_des' => 0, 'team_name' => 0, 'join_date' => 0, 'leave_date' => 0, 'status' => 0);

		$user_header = array_keys($csv->data[0]);

	foreach($user_header as $i=>$value)
    {
        if(!in_array($value, array_keys($std_header))) {
        	drupal_set_message(t('Field '.'"'.$value.'"'.' does not match any expected field'), 'error');
        	$form_state['csv_error_flag'] = TRUE;
        }
        else
            $std_header[$value]++;
    }
    foreach($std_header as $key=>$value)
    {
        if($value > 1) {
        	drupal_set_message(t("Multiple values for field ".$key), 'error');
        	$form_state['csv_error_flag'] = TRUE;
        }
        else if($value == 0 and !in_array($key, array('emp_id', 'emp_name', 'emp_des', 'team_name', 'join_date', 'leave_date', 'status')))
           { drupal_set_message(t("Field ".$key." is missing"), 'error'); $form_state['csv_error_flag'] = TRUE; }
    }

    if(isset($form_state['csv_error_flag']))
    	return;

    // Check CSV DATA

    foreach($csv->data as $rno=>$row)
    {
        foreach($row as $key=>$value)
        {
            if( !in_array($key, array('emp_id', 'emp_name', 'status')) and ($value == '' or $value == NULL))
                { drupal_set_message(t("Missing value for field '".$key."' in row ".($rno+1)), 'error'); $form_state['csv_error_flag'] = TRUE; }
        }
    }

}

function upload_csv_submit($form, &$form_state) {
	
	if(isset($form_state['csv_error_flag']))
        return;

    $file_path = $_FILES['files']['tmp_name']['csv_file'];
    $csv = new ParseCsv\Csv($file_path);
    $fields = array_keys($csv->data[0]);
    $insertquery = db_insert('emp_form_data')->fields($fields);

    foreach($csv->data as $i=>$record)
    {   
        if($record['emp_id'] == NULL or $record['emp_id'] == '') {
        	drupal_set_message(t('No Employee Name in CSV'),'error');
            return;
            }	// $record['starttime'] = "00:00";
        else if($record['emp_name'] == NULL or $record['emp_name'] == '') {
            drupal_set_message(t('No Employee Name in CSV'),'warning');
            return;	// $record['endtime'] = "00:00";
        }
        $insertquery->values($record);
    }
    $insertquery->execute();
    drupal_set_message(t("Successfully submitted"));
}

//*********** View Employee Data **************

function view_emp_form() {

	if(user_is_anonymous())	{
		$results = db_query("SELECT * FROM {emp_form_data}");
		$header = array(t('Employee ID'), t('Name'), t('Designation'), t('Team Name'), t('Joining Date'), t('Leaving Date'), t('Status'));
		$rows =array();
		foreach($results AS $result) {
		
				$rows[] = array(
				$get_emp_id = $result->emp_id,
				$emp_name = $result->emp_name,
				$result->emp_des,
				$result->team_name,
				$result->join_date,
				$result->leave_date,
				$result->status,
				);
			}

			$output = '';

				if(!empty($rows)) {

					$output = theme('table', array(
					'header'=>$header,
					'rows'=>$rows,
					));
				}
				else {
					$output .= t('There is no employees in the list ');
					$output .= l(t('Click here to add Employee'),"/emp_form/add");
					$output .= t(' or ');
					$output .= l(t('Upload CSV'),"/emp_form/upload");
				}

	}

	else {

			//**************************** SORT BY EMPLOYEE ID ****************************
			$emp_id_sort = trim(current_path(), '/emp_form/view/');
			if($emp_id_sort == 'sortby/emp_id/ASC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_id` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_id_sort == 'sortby/emp_id/DESC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_id` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			//**************************** SORT BY EMPLOYEE NAME ****************************

			$emp_name_sort = trim(current_path(), '/emp_form/view');
			if($emp_name_sort == 'sortby/emp_name/ASC') {
				
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_name` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/DESC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_name_sort == 'sortby/emp_name/DESC') {
				
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_name` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			//**************************** SORT BY EMPLOYEE DESIGNATION ****************************

			$emp_des_sort = trim(current_path(), '/emp_form/view/');
			if($emp_des_sort == 'sortby/emp_des/ASC') {
				
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_des` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_des_sort == 'sortby/emp_des/DESC') {
				
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `emp_des` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			// ******************************* SORT BY EMPLOYEE TEAM NAME  ****************************


			$emp_team_name_sort = trim(current_path(), '/emp_form/view');
			if($emp_team_name_sort == 'sortby/emp_team_name/ASC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `team_name` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_team_name_sort == 'sortby/emp_team_name/DESC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `team_name` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			//**************************** SORT BY EMPLOYEE JOINING DATE ****************************


			$emp_join_date_sort = trim(current_path(), '/emp_form/view');
			if($emp_join_date_sort == 'sortby/emp_join_date/ASC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `join_date` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_join_date_sort == 'sortby/emp_join_date/DESC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `join_date` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			//**************************** SORT BY EMPLOYEE LEAVING DATE ****************************


			$emp_leave_date_sort = trim(current_path(), '/emp_form/view');
			if($emp_leave_date_sort == 'sortby/emp_leave_date/ASC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `leave_date` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}
			if($emp_leave_date_sort == 'sortby/emp_leave_date/DESC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `leave_date` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}

			//**************************** SORT BY EMPLOYEE STATUS ****************************

			$emp_status_sort = trim(current_path(), '/emp_form/view');
			if($emp_leave_date_sort == 'sortby/status/ASC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `status` ASC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by DESC')))),
					l(t('Status'),"emp_form/view/sortby/status/DESC",array('attributes' => array('title' => t('Sort by DESC')))),
					t('Action'));
			}
			if($emp_status_sort == 'sortby/status/DESC') {
				$results = db_query("SELECT * FROM {emp_form_data} ORDER BY `status` DESC");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			if( $emp_id_sort == NULL and $emp_name_sort == NULL and $emp_des_sort == NULL and $emp_team_name_sort == NULL and $emp_join_date_sort == NULL and $emp_leave_date_sort == NULL and $emp_status_sort == NULL )
			{
				$results = db_query("SELECT * FROM {emp_form_data}");
				$header = array(
					l(t('Employee ID'),"emp_form/view/sortby/emp_id/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Name'),"emp_form/view/sortby/emp_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Designation'),"emp_form/view/sortby/emp_des/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Team Name'),"emp_form/view/sortby/emp_team_name/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Joining Date'),"emp_form/view/sortby/emp_join_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Leaving Date'),"emp_form/view/sortby/emp_leave_date/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					l(t('Status'),"emp_form/view/sortby/status/ASC",array('attributes' => array('title' => t('Sort by ASC')))),
					t('Action'));
			}


			$rows =array();
			foreach($results AS $result) {
		
				$rows[] = array(
				$get_emp_id = $result->emp_id,
				$emp_name = $result->emp_name,
				$result->emp_des,
				$result->team_name,
				$result->join_date,
				$result->leave_date,
				$result->status,
				$action = $edit[] = l('<span class = "button">'.t('Edit').'</span>', "emp_form/edit/$get_emp_id",array('attributes' => array('title' => t('Edit Employee.'), 'class' => 'button'), 'html' => 'TRUE')).' • '.$delete[] = l('<span>'.t('Delete').'</span>', "emp_form/delete/$get_emp_id",array('attributes' => array('title' => t('Delete Employee.'), 'class' => 'button'), 'html' => 'TRUE')).'',
				);
			}

			$output = '';

				if(!empty($rows)) {

					$output = theme('table', array(
					'header'=>$header,
					'rows'=>$rows,
					));
					$output .= l(t('Click here to add Employee'),"/emp_form/add");
					$output .= t(' or ');
					$output .= l(t('Upload CSV'),"/emp_form/upload");
					$output .= t(' or ');
					$output .= l(t('Back to View'),"/emp_form/view");
				}
				else {
					$output .= t('There is no employees in the list ');
					$output .= l(t('Click here to add Employee'),"/emp_form/add");
					$output .= t(' or ');
					$output .= l(t('Upload CSV'),"/emp_form/upload");
				}

	}
	return $output;
}


//*********** Edit database table as row ****************


function edit_emp_data($form , &$form_state) {

		$cl = trim(current_path(), '/emp_form/edit');		// Get the Employee ID for Query
		$emp_id ='';
		$results = db_query("select * from {emp_form_data} where emp_id = '$cl'");
		foreach ($results as $result) {
			$emp_name = $result->emp_name;
			$emp_des = $result->emp_des;
			$tid = $result->tid;
			$emp_id = $result->emp_id;
			$team_name = $result->team_name;
			$join_date = $result->join_date;
			$leave_date = $result->leave_date;
			$status = $result->status;

			
		}

	if($emp_id == $cl) {

	$form['emp_id'] = array(
		'#title' => t('Employee ID'),
		'#description' => t('The Employee\'s ID'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $emp_id,
	);

	$form['emp_name'] = array(
		'#title' => t('Employee Name'),
		'#description' => t('The Employee\'s name'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $emp_name,
	);

	$form['emp_des'] = array(
		'#title' => t('Employee Designation'),
		'#description' => t('The Employee\'s Designation'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $emp_des,
	);

	$form['team_name'] = array(
		'#title' => t('Team Name'),
		'#description' => t('The Team\'s Name'),
		'#type' => 'textfield',
		'#required' => FALSE,
		'#default_value' => $team_name,
	);

	$form['join_date'] = array(
		'#type' => 'date_popup',
		'#date_format' => 'j F Y',
		'#title' => t('Joing Date'),
		'#default_value' => $join_date,
		'#datepicker_options' => array('yearRange' => "2005:+5"),
	);

	$form['leave_date'] = array(
		'#type' => 'date_popup',
		'#date_format' => 'j F Y',
		'#title' => t('Leaving Date'),
		'#default_value' => $leave_date,
		'#datepicker_options' => array('yearRange' => "2005:+5"),
	);

	$form['status'] = array(
		'#title' => t('Employee Status'),
		'#type' => 'radios',
		'#description' => t('Employee Status'),
		'#default_value' => $status,
		'#required' => TRUE,
		'#options' =>array('Active' => t('Active'),'Inactive' => t('Inactive'),),
	);

	$form['tid'] = array(
		'#title' => t('Primary Key'),
		'#description' => t('Serial Number'),
		'#type' => 'hidden',
		'#required' => FALSE,
		'#default_value' => $tid,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['cancel'] = array(
		'#type' => 'submit',
		'#value' => t('Cancel'),
		'#submit' => array('edit_emp_form_cancel'),
	);
			
	return $form;
	}

	else {
		drupal_set_message(t('Please Enter valid Employee ID'),'error');
		drupal_goto("/emp_form/view");

	}
}

function edit_emp_data_submit($form, &$form_state) {
	// Here you are use DB Query like insert data of employee in the table
	// 'first_name' => $form_state['values']['first_name'],

			$tid = $form_state['values']['tid'];
			db_merge('emp_form_data')
				->key(array('tid' => $tid))
				->fields(array(
					'emp_id' => $form_state['values']['emp_id'],
					'emp_name' => $form_state['values']['emp_name'],
					'emp_des' => $form_state['values']['emp_des'],
					'team_name' => $form_state['values']['team_name'],
					'join_date' => $form_state['values']['join_date'],
					'leave_date' => $form_state['values']['leave_date'],
					'status' => $form_state['values']['status'],
				))
				->execute();
			
			drupal_set_message(t('Employee Details is edited'));
			drupal_goto("/emp_form/view");
}

//*********** Delete database table as row ****************




function delete_emp_data_submit($form , &$form_state) {
		$cl = trim(current_path(), '/emp_form/delete'); 	// Get the Employee ID for Query

			db_delete('emp_form_data')
				->condition('emp_id', $cl)
				->execute();

	drupal_get_messages();
	drupal_set_message(t('Employee is deleted'));
	drupal_goto("/emp_form/view");
}

function delete_emp_data($form , &$form_state) {
	$cl = trim(current_path(), '/emp_form/delete');

	$header = array(t('Employee ID'), t('Name'), t('Designation'));
	$rows =array();

	$results = db_query("select * from {emp_form_data} where emp_id = '$cl'");
		foreach ($results as $result) {
			$rows[] = array(
			$get_emp_id = $result->emp_id,
			$emp_name = $result->emp_name,
			$emp_des = $result->emp_des,
		);
		}

	// $output = theme('table', array('header'=>$header,'rows'=>$rows));
	drupal_set_message(t("Do you want to delete *$emp_name* $emp_des Employee?"),'warning');
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
		'#submit' => array('delete_emp_data_submit'),
	);

	$form['cancel'] = array(
		'#type' => 'submit',
		'#value' => t('Cancel'),
		'#submit' => array('view_emp_form_cancel'),
	);

	// return $form;

	return array($form);

}

function view_emp_form_cancel($form ,&$form_state) {
	drupal_get_messages();
	drupal_goto("/emp_form/view");
}

function edit_emp_form_cancel($form, &$form_state) {
	drupal_get_messages();
	drupal_goto("/emp_form/view");
}