<?php
/**
	* impliments hook_help()
	*
	* @param path
*/

drupal_add_library('system', 'drupal.ajax');

function emp_form_help($path, $arg) {
	switch ($path) {
		case "admin/help#emp_form":
			return t("Display links to nodes created on this date click here for github");
			break;
	}
}

//*********** Employee Form Menus**************

function emp_form_menu() {
	$items = array();
	// setup url */emp_form
	$items['emp_form/add'] = array(
		'title' => 'Employee Form',
		'type' => MENU_LOCAL_TASK,
		'description' => 'fill the emp details',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('emp_form_my_form'),
		'access arguments' => array('submit emp_form'),
	);

	$items['emp_form/view'] = array(
		'title' => 'List of Employee',
		'type' => MENU_LOCAL_TASK,
		'description' => 'fill the emp details',
		'page callback' => 'view_emp_form',
		'access arguments' => array('view view_emp_form'),
	);

	$items['emp_form/upload'] = array(
		'title' => 'Upload CSV File',
		'type' => MENU_LOCAL_TASK,
		'description' => 'Choose CSV File',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_csv'),
		'access arguments' => array('upload upload_csv'),
	);

        //******************** Sorting **********************

		$items['emp_form/view?order=field_emp_id&sort=desc'] = array(
		'title' => 'List of Employee',
		'type' => MENU_LOCAL_TASK,
		'description' => 'Order By Employee ID',
		'page callback' => 'view_emp',
		'access arguments' => array('view view_emp_form'),
		);

		//************ Edit Employee Data By ID *************

		$items['emp_form/edit/%'] = array(
			'title' => 'Edit Employee Data',
			'type' => MENU_LOCAL_TASK,
			'description' => 'Edit Employee By ID',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('edit_emp_data'),
			'access arguments' => array('edit emp_form_data_edit'),
		);

		//*********** Delete Employee Data By ID ************

		$items['emp_form/delete/%'] = array(
			'title' => 'Delete Employee Data',
			'type' => MENU_LOCAL_TASK,
			'description' => 'Delete Employee By ID',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('delete_emp_data'),
			'access arguments' => array('delete emp_form_data_delete'),
			// 'delivery callback' => 'ajax_deliver',
		);


	return $items;
}

//*********** Employee Form permission **************

function emp_form_permission() {
	return array(
		'submit emp_form' => array(
			'title' => t('submit emp_form'),
			'description' => t('Submit the emp_form form'),
		),

		'view view_emp_form' => array(
			'title' => t('View Form'),
			'description' => t('View Forms'),
		),

		'upload upload_csv' => array(
			'title' => t('Upload CSV'),
			'description' => t('Upload Csv file'),
		),

		'edit emp_form_data_edit' => array(
			'title' => t('Edit Employee Data'),
			'description' => t('Edit Employee by ID'),
		),

		'delete emp_form_data_delete' => array(
			'title' => t('Delete Employee Data'),
			'description' => t('Delete Employee Data by ID'),
		),
	);
}

//*********** Insert Individual Employee Data **************

function emp_form_my_form($form, &$form_state) {
	$form['first_name'] = array(
		'#title' => t('First Name'),
		'#description' => t('The Employee\'s first name'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['middle_name'] = array(
		'#title' => t('Middle Name'),
		'#description' => t('The Employee\'s Middle Name'),
		'#type' => 'textfield',
		'#required' => FALSE,
	);

	$form['last_name'] = array(
		'#title' => t('Last Name'),
		'#description' => t('The Employee\'s Last Name'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['emp_des'] = array(
		'#title' => t('Employee Designation'),
		'#description' => t('The Employee\'s Designation'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['emp_id'] = array(
		'#title' => t('Employee ID'),
		'#description' => t('The Employee\'s ID'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	return $form;
}


function emp_form_my_form_validate($form, &$form_state) {

}

function emp_form_my_form_submit($form, &$form_state) {
	// Here you are use DB Query like insert data of employee in the table
	db_insert('emp_form_data')
		->fields(array(
			'first_name' => $form_state['values']['first_name'],
			'middle_name' => $form_state['values']['middle_name'],
			'last_name' => $form_state['values']['last_name'],
			'emp_des' => $form_state['values']['emp_des'],
			'emp_id' => $form_state['values']['emp_id'],
		))
		->execute();

	drupal_set_message(t('Your Form submitted'));
}


//*********** Upload CSV FILE **************

function upload_csv($form ,&$form_state) {

	$form['csv_upload'] = array(
	'#type' => 'file',
	'#title' => t('Choose a csv file'),
	'#title_display' => 'invisible',
	'#size' => 22,
	'#upload_validators' => array('file_clean_name' => array()),
	);

	$form['upload'] = array(
		'#type' => 'submit',
		'#value' => 'Upload',
	);

	return $form;
}

function upload_csv_submit($form, &$form_state) {
	$file = $form_state['values']['csv_upload'];
	// $file->status = FILE_STATUS_TEMPORARY;
	$file->filename = str_replace(' ', '_', $file->filename);
	file_save($file);

	$csv_file = file_load($file->fid);
	$file = fopen($csv_file->uri, "r");
    $batch_number = time()."-".rand(1,99);
    $time_captured = time();

    while(! feof($file))
    {
    	$employees = fgetcsv($file);
			global $user;
		db_insert('emp_form_data')
			->fields(array(
				'emp_id' => $employees[0],
				'first_name' => $employees[1],
				'middle_name' => $employees[2],
				'last_name' => $employees[3],
				'emp_des' => $employees[4],

			))
			->execute();
    }
    fclose($file);
    file_delete($csv_file);												// Delete Upload file
    drupal_set_message(t('Your CSV added to database'));
}

function file_clean_name($file) {
  $file->filename = str_replace(' ', '_', $file->filename);
}

function upload_csv_validate($form, &$form_state) {
		$validators = array('file_validate_extensions' => array('csv'));

	$file = file_save_upload('csv_upload', $validators);

	 if (isset($file)) {
	 	if ($file) {
	 		$form_state['values']['csv_upload'] = $file;
	 	}
	 	 else {
      form_set_error('csv_upload', t('The file could not be uploaded.'));
    }
  }
}


//*********** View Employee Data **************

function view_emp_form() {



	

	if(user_is_anonymous())	{
		$results = db_query("SELECT * FROM {emp_form_data}");
		$header = array(t('Employee ID'), t('Name'), t('Designation'));
		$rows =array();
		foreach($results AS $result) {
		
				$rows[] = array(
				$get_emp_id = $result->emp_id,
				$result_full_name = $result->first_name.' '.$result->middle_name.' '.$result->last_name,
				$result->emp_des,
				);
			}

			$output = '';

				if(!empty($rows)) {

					$output = theme('table', array(
					'header'=>$header,
					'rows'=>$rows,
					'attributes' => array(
						'id' => 'sort-table'
						)
					));
				}
				else {
					$output .= t('There is no employees in the list ');
					$output .= l(t('Click here to add Employee'),"/emp_form/add");
					$output .= t(' or ');
					$output .= l(t('Upload CSV'),"/emp_form/upload");
				}

	}

	else {
			$results = db_query("SELECT * FROM {emp_form_data}");
			$header = array(t('Employee ID'), t('Name'), t('Designation'), t('Action'));
			$rows =array();
			foreach($results AS $result) {
		
				$rows[] = array(
				$get_emp_id = $result->emp_id,
				$result_full_name = $result->first_name.' '.$result->middle_name.' '.$result->last_name,
				$result->emp_des,
				$action = $edit[] = l('<span>'.t('Edit').'</span>', "emp_form/edit/$get_emp_id",array('attributes' => array('title' => t('Edit Employee.'), 'class' => 'button'), 'html' => 'TRUE')).'| '.$delete[] = l('<span>'.t('Delete').'</span>', "emp_form/delete/$get_emp_id",array('attributes' => array('title' => t('Delete Employee.'), 'class' => 'button'), 'html' => 'TRUE')).'',
				);
			}

			$output = '';

				if(!empty($rows)) {

					$output = theme('table', array(
					'header'=>$header,
					'rows'=>$rows,
					'attributes' => array(
						'id' => 'sort-table'
						)
					));
				}
				else {
					$output .= t('There is no employees in the list ');
					$output .= l(t('Click here to add Employee'),"/emp_form/add");
					$output .= t(' or ');
					$output .= l(t('Upload CSV'),"/emp_form/upload");
				}

	}
	return $output;
}


//*********** Edit database table as row ****************


function edit_emp_data($form , &$form_state) {

		$cl = trim(current_path(), '/emp_form/edit');		// Get the Employee ID for Query

		$results = db_query("select * from {emp_form_data} where emp_id = $cl");
		foreach ($results as $result) {
			$first_name = $result->first_name;
			$middle_name = $result->middle_name;
			$last_name = $result->last_name;
			$emp_des = $result->emp_des;
			$tid = $result->tid;
			$emp_id = $result->emp_id;
		}


	$form['first_name'] = array(
		'#title' => t('First Name'),
		'#description' => t('The Employee\'s first name'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $first_name,
	);

	$form['middle_name'] = array(
		'#title' => t('Middle Name'),
		'#description' => t('The Employee\'s Middle Name'),
		'#type' => 'textfield',
		'#required' => FALSE,
		'#default_value' => $middle_name,
	);

	$form['last_name'] = array(
		'#title' => t('Last Name'),
		'#description' => t('The Employee\'s Last Name'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $last_name,
	);

	$form['emp_des'] = array(
		'#title' => t('Employee Designation'),
		'#description' => t('The Employee\'s Designation'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $emp_des,
	);

	$form['emp_id'] = array(
		'#title' => t('Employee ID'),
		'#description' => t('The Employee\'s ID'),
		'#type' => 'hidden',
		'#required' => FALSE,
		'#default_value' => $emp_id,
	);

	$form['tid'] = array(
		'#title' => t('Primary Key'),
		'#description' => t('Serial Number'),
		'#type' => 'hidden',
		'#required' => FALSE,
		'#default_value' => $tid,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
			
	return $form;
}

function edit_emp_data_submit($form, &$form_state) {
	// Here you are use DB Query like insert data of employee in the table
	// 'first_name' => $form_state['values']['first_name'],

	$tid = $form_state['values']['tid'];
	
	db_merge('emp_form_data')
		->key(array('tid' => $tid))
		->fields(array(
			'first_name' => $form_state['values']['first_name'],
			'middle_name' => $form_state['values']['middle_name'],
			'last_name' => $form_state['values']['last_name'],
			'emp_des' => $form_state['values']['emp_des'],
		))
		->execute();

	drupal_set_message(t('Employee Details is edited'));
	drupal_goto("/emp_form/view");
}

//*********** Delete database table as row ****************




function delete_emp_data_submit($form , &$form_state) {
		$cl = trim(current_path(), '/emp_form/delete'); 	// Get the Employee ID for Query

			db_delete('emp_form_data')
				->condition('emp_id', $cl)
				->execute();

			drupal_set_message(t('Employee is deleted'));

			drupal_goto("/emp_form/view");
}

function delete_emp_data($form , &$form_state) {
	$cl = trim(current_path(), '/emp_form/delete');

	$header = array(t('Employee ID'), t('Name'), t('Designation'));
	$rows =array();

	$results = db_query("select * from {emp_form_data} where emp_id = $cl");
		foreach ($results as $result) {
			$rows[] = array(
			$get_emp_id = $result->emp_id,
			$result_full_name = $result->first_name.' '.$result->middle_name.' '.$result->last_name,
			$result->emp_des,
		);
		}

	$output = theme('table', array('header'=>$header,'rows'=>$rows));

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
		'#submit' => array('delete_emp_data_submit'),
	);

	$form['cancel'] = array(
		'#type' => 'submit',
		'#value' => t('Cancel'),
		'#submit' => array('view_emp_form_cancel'),
		// '#action' => url('emp_form/view'),
		// 'page callback' => 'view_emp_form',
	);

	// return $form;

	return array($form);

}

function view_emp_form_cancel($form ,&$form_state) {

	drupal_goto("/emp_form/view");
}